server:
  port: 8130  #服务端口
spring:

  profiles:
    active: dev #环境配置
  application:
    name: service-oss #服务名
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: LTAI5tJUK2Prnu75ibJUr86Z
    keySecret: smw2vCVHFzsoqBxQCrGMO0xFWvfFZj
    bucketName: maple-srb-file-20220213