server:
  port: 8140  #服务端口
spring:

  profiles:
    active: dev #环境配置
  application:
    name: service-minio #服务名
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  #spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    #    password:  #默认为空
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

# spring节点下 nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址

# spring节点下 openFeign
feign:
  client:
    config:
      default:
        connectTimeout: 10000 #连接超时配置
        readTimeout: 600000 #执行超时配置
  #开启Feign对Sentinel的支持
  #feign:
  sentinel:
    enabled: true

logging:
  level:
    com.atguigu.srb.sms.client.CoreUserInfoClient: DEBUG #以什么级别监控哪个接口

#minio 文件服务配置
minio:
  enable: true  # 必须配置 true
  enableHttps: false # 是否使用https
  endpoint: http://192.168.50.249:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: srb

